### ISSUE TITLE
make build error with maven -f option

### ISSUE THREAD

**Issue by tynanford** [ChannelFinder/ChannelFinder-env#8]
https://github.com/ChannelFinder/ChannelFinder-env/blob/e184e07406528fa2f78991c4fe99e3286b7c7d8f/configure/RULES_SRC#L54

Hey Han, 

I saw build got changed and no longer specifies pom.xml in build command. Is this by design? On centos 7 for me, make build only works if I add pom.xml to this line:

$(QUIET) mvn $(CF_MVN_OPTS) -f $(CF_SRC_PATH)/pom.xml clean install -Dmaven.test.skip=true

Also for me, CF_SRC_PATH = ChannelFinder-SpringBoot-src

**Comment by jeonghanlee** [comment]
I forgot to revert my test, somehow debian based Linux or latest maven works fine. I revert and will push it.

**Comment by jeonghanlee** [comment]
Could you test it within CentOS?

**Comment by tynanford** [comment]
It is working now thanks. Maybe it is the maven version on centos.

`$ mvn --version
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
`
